version: '3.8'

services:
  # 1. Neo4j: 负责存储图谱
  neo4j:
    image: neo4j:5.15.0
    container_name: bird_neo4j
    environment:
      - NEO4J_AUTH=neo4j/deng9q768 # 设置账号密码
      # - NEO4J_PLUGINS=["apoc"] # 开启图算法插件
    ports:
      - "7474:7474" # Neo4j 浏览器 WebUI 端口
      - "7687:7687" # Bolt 协议 API 端口
    volumes:
      - ./docker_data/neo4j_data:/data
    restart: always

  # 2. Postgres (带 PGVector): 负责存储高维度的向量数据，突破 JSON 存储的极限
  postgres:
    image: pgvector/pgvector:pg16
    container_name: bird_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lightrag_password
      - POSTGRES_DB=lightrag
    ports:
      - "5432:5432"
    volumes:
      - ./docker_data/postgres_data:/var/lib/postgresql/data
    restart: always