"""Taxonomy constants for Step 1."""

ORDER = "order"
FAMILY = "family"
GENUS = "genus"
SPECIES = "species"
SUBSPECIES = "subspecies"

VALID_RANKS = {ORDER, FAMILY, GENUS, SPECIES, SUBSPECIES}

AVILIST = "AviList"
CLEMENTS = "Clements"
BOW = "BOW"
CORNELL = "Cornell"

EXACT_MATCH = "EXACT_MATCH"
NAME_MATCH = "NAME_MATCH"
CODE_MATCH = "CODE_MATCH"
AVIBASE_MATCH = "AVIBASE_MATCH"
UNRESOLVED = "UNRESOLVED"
CONFLICT = "CONFLICT"

RANK_MISMATCH = "RANK_MISMATCH"
FAMILY_MISMATCH = "FAMILY_MISMATCH"
GENUS_MISMATCH = "GENUS_MISMATCH"
NAME_MISMATCH = "NAME_MISMATCH"
SPLIT_LUMP_DRIFT = "SPLIT_LUMP_DRIFT"
