"""Central predicate taxonomy for V2.1 claims."""

from __future__ import annotations

PREDICATE_TO_RELATION = {
    "INHABITS": "INHABITS",
    "OCCURS_IN": "OCCURS_IN",
    "BREEDS_IN": "BREEDS_IN",
    "WINTERS_IN": "WINTERS_IN",
    "EATS": "EATS",
    "FORAGES_BY": "FORAGES_BY",
    "HAS_TRAIT": "HAS_TRAIT",
    "HAS_VOCALIZATION": "HAS_VOCALIZATION",
    "NESTS_AT": "NESTS_AT",
    "THREATENED_BY": "THREATENED_BY",
    "HAS_STATUS": "HAS_STATUS",
    "SIMILAR_TO": "SIMILAR_TO",
    "HYBRIDIZES_WITH": "HYBRIDIZES_WITH",
    "REQUIRES_RESEARCH": "REQUIRES_RESEARCH",
    "MANAGED_BY": "MANAGED_BY",
}

ENTITY_CLAIM_PREDICATES = set(PREDICATE_TO_RELATION)

NUMERIC_PREDICATES = {
    "BODY_LENGTH",
    "BODY_MASS",
    "ELEVATION_RANGE",
    "CLUTCH_SIZE",
    "INCUBATION_PERIOD",
    "FLEDGING_PERIOD",
    "LIFESPAN",
}

TEXT_SUMMARY_PREDICATES = {
    "TAXONOMY_NOTE",
    "BREEDING_PROFILE",
    "CONSERVATION_PROFILE",
    "FUTURE_RESEARCH",
}
