"""Relationship type constants for KG V2."""

CONTAINS_FAMILY = "CONTAINS_FAMILY"
CONTAINS_GENUS = "CONTAINS_GENUS"
CONTAINS_SPECIES = "CONTAINS_SPECIES"
CONTAINS_SUBSPECIES = "CONTAINS_SUBSPECIES"
HAS_ALIAS = "HAS_ALIAS"
MAPPED_TO = "MAPPED_TO"
CONFLICTS_WITH = "CONFLICTS_WITH"

BELONGS_TO = "BELONGS_TO"
HAS_SUBSPECIES = "HAS_SUBSPECIES"
INHABITS = "INHABITS"
OCCURS_IN = "OCCURS_IN"
BREEDS_IN = "BREEDS_IN"
WINTERS_IN = "WINTERS_IN"
EATS = "EATS"
FORAGES_BY = "FORAGES_BY"
HAS_TRAIT = "HAS_TRAIT"
HAS_VOCALIZATION = "HAS_VOCALIZATION"
NESTS_AT = "NESTS_AT"
THREATENED_BY = "THREATENED_BY"
HAS_STATUS = "HAS_STATUS"
SIMILAR_TO = "SIMILAR_TO"
HYBRIDIZES_WITH = "HYBRIDIZES_WITH"
REQUIRES_RESEARCH = "REQUIRES_RESEARCH"
MANAGED_BY = "MANAGED_BY"

HAS_ASPECT = "HAS_ASPECT"
HAS_DERIVED_SUMMARY = "HAS_DERIVED_SUMMARY"
SUPPORTED_BY = "SUPPORTED_BY"

HAS_FACT = "HAS_FACT"
OBJECT = "OBJECT"

RELATED_TO = "RELATED_TO"
CONFUSED_WITH = "CONFUSED_WITH"
SISTER_TO = "SISTER_TO"

ALL_RELATION_TYPES = (
    CONTAINS_FAMILY,
    CONTAINS_GENUS,
    CONTAINS_SPECIES,
    CONTAINS_SUBSPECIES,
    HAS_ALIAS,
    MAPPED_TO,
    CONFLICTS_WITH,
    BELONGS_TO,
    HAS_SUBSPECIES,
    INHABITS,
    OCCURS_IN,
    BREEDS_IN,
    WINTERS_IN,
    EATS,
    FORAGES_BY,
    HAS_TRAIT,
    HAS_VOCALIZATION,
    NESTS_AT,
    THREATENED_BY,
    HAS_STATUS,
    SIMILAR_TO,
    HYBRIDIZES_WITH,
    REQUIRES_RESEARCH,
    MANAGED_BY,
    HAS_ASPECT,
    HAS_DERIVED_SUMMARY,
    SUPPORTED_BY,
    HAS_FACT,
    OBJECT,
    RELATED_TO,
    CONFUSED_WITH,
    SISTER_TO,
)
